#!/usr/bin/env perl
use strict;
use warnings;

# use local author libraries
use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(MIDI-Drummer-Tiny MIDI-Util Music-Duration Music-MelodicDevice-Ornamentation);
use MIDI::Drummer::Tiny ();
use Music::Duration ();

Music::Duration::tuplet('hn', 'X', 5);

my $d = MIDI::Drummer::Tiny->new(
    file   => "$0.mid",
    bpm    => 60,
    reverb => 15,
);

$d->sync(
    \&cymbals,
    \&skins,
);

$d->write;

sub cymbals {
    for my $i (1 .. 12) {
        if ($i == 1) {
            $d->rest('d6');
            $d->note('d90', $d->pedal_hh);
        }
        elsif ($i == 9) {
            $d->note($d->quarter, $d->pedal_hh, $d->crash1);
        }
        else {
            $d->note($d->quarter, $d->pedal_hh);
        }
    }
}

sub skins {
    # 1
    $d->flam($d->quarter, $d->kick, $d->snare);

    $d->note($d->thirtysecond, $d->snare);
    $d->note($d->thirtysecond, $d->snare);
    $d->note($d->thirtysecond, $d->kick);
    $d->note($d->thirtysecond, $d->kick);
    $d->note($d->eighth, $d->snare);

    $d->note($d->thirtysecond);
    $d->note($d->thirtysecond, $d->snare);
    $d->note($d->sixteenth, $d->snare);
    $d->note($d->eighth, $d->kick);

    $d->rest($d->sixteenth);
    $d->roll($d->eighth, $d->thirtysecond);
    $d->note($d->sixteenth, $d->kick);

    # 2
    $d->note($d->triplet_sixteenth, $d->kick);
    $d->note($d->triplet_sixteenth, $d->kick);
    $d->note($d->triplet_sixteenth, $d->snare);
    $d->note($d->eighth, $d->kick);

    $d->note($d->triplet_eighth, $d->kick);
    $d->note($d->triplet_sixteenth, $d->kick);
    $d->roll($d->eighth, $d->thirtysecond);

    $d->rest('Xhn');
    $d->flam('Xhn', $d->hi_tom);
    $d->flam('Xhn', $d->snare);
    $d->flam('Xhn', $d->low_tom);
    $d->flam('Xhn', $d->hi_floor_tom);

    # 3
    
}
